version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  watcher:
    build:
      context: .
      dockerfile: Dockerfile.watcher
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./plugins:/app/plugins
